---
services:
  api:
    build: .
    environment:
      FOOTBALL_APIKEY: apiKey
      DATABASE_DSN: challenge:challenge@tcp(db:3306)/challenge
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: challenge
      MYSQL_USER: challenge
      MYSQL_PASSWORD: challenge
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge
    name: backend